export const TRANSLATIONS = {
  en: {
    appName: "Code Guardian AI",
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    streak: "Day Streak",
    continue: "Continue Learning",
    courses: "Courses",
    settings: "Settings",
    logout: "Logout",
    askAI: "Ask AI Tutor",
    practice: "Practice",
    theory: "Theory",
    example: "Example",
    task: "Task",
    submit: "Submit Code",
    welcome: "Welcome back, Guardian!",
    nextDay: "Next Day Unlocks Tomorrow",
    completed: "Completed",
    locked: "Locked",
    aiPlaceholder: "Ask me anything about this lesson...",
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
  },
  vi: {
    appName: "Code Guardian AI",
    login: "Đăng nhập",
    register: "Đăng ký",
    email: "Email",
    password: "Mật khẩu",
    streak: "Chuỗi ngày",
    continue: "Tiếp tục học",
    courses: "Khóa học",
    settings: "Cài đặt",
    logout: "Đăng xuất",
    askAI: "Hỏi Trợ lý AI",
    practice: "Thực hành",
    theory: "Lý thuyết",
    example: "Ví dụ",
    task: "Nhiệm vụ",
    submit: "Nộp bài",
    welcome: "Chào mừng trở lại, Guardian!",
    nextDay: "Ngày tiếp theo sẽ mở vào ngày mai",
    completed: "Đã hoàn thành",
    locked: "Đã khóa",
    aiPlaceholder: "Hỏi tôi bất cứ điều gì về bài học này...",
    language: "Ngôn ngữ",
    theme: "Giao diện",
    light: "Sáng",
    dark: "Tối",
  }
};
